---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - port: 6379
      name: redis-port
      targetPort: 6379
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      restartPolicy: Always
      containers:
        - name: redis
          image: redis:4.0.1-alpine
          ports:
            - containerPort: 6379
