version: '3'

services:
  rjupyter:
    image: jupyter/r-notebook:latest
    restart: always
    ports:
      - 8884:8888
    volumes:
      - ./data:/home/jovyan/
      - ./data/runtime:/home/jovyan/.local/share/jupyter/runtime/
