version: "3"

services:
  vsftpd:
    image: fauria/vsftpd:latest
    restart: always
    ports:
      - 0.0.0.0:120:20
      - 0.0.0.0:121:21
      - 21100-21110:21100-21110
    volumes:
      - ./data:/home/vsftpd/username
    environment:
      - FTP_USER=username
      - FTP_PASS=password
      - FILE_OPEN_MODE=0777
      - PASV_ADDRESS=0.0.0.0
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110