version: "3"

services:
  vsftpd:
    image: fauria/vsftpd:latest
    restart: always
    ports:
      - 0.0.0.0:120:20
      - 0.0.0.0:121:21
      - 21100-21110:21100-21110
    volumes:
      - ./data:/home/vsftpd
      - ./etc/vsftpd.conf:/etc/vsftpd/vsftpd.conf 
    environment:
      - FTP_USER=username
      - FTP_PASS=password